import os
import requests
from typing import Dict, Any, Optional
from .base import BasePublisher

class LinkedInPublisher(BasePublisher):
    def __init__(self):
        super().__init__()
        self.access_token = os.getenv("LINKEDIN_ACCESS_TOKEN")
        self.author_urn = os.getenv("LINKEDIN_AUTHOR_URN") # e.g., urn:li:person:12345 or urn:li:organization:67890

    def publish(self, text: str, media_url: Optional[str] = None) -> Dict[str, Any]:
        """
        Publishes content to LinkedIn.
        Handles the 3-step image upload flow if media_url is provided.
        """
        if not self.access_token or not self.author_urn:
            return {"error": "CONFIG_ERROR", "message": "LinkedIn credentials (TOKEN, AUTHOR_URN) not configured."}

        headers = {
            "Authorization": f"Bearer {self.access_token}",
            "Content-Type": "application/json",
            "X-Restli-Protocol-Version": "2.0.0"
        }

        asset_urn = None

        try:
            # Step 1: Upload Image if exists
            if media_url:
                # 1.1 Register Upload
                register_url = "https://api.linkedin.com/v2/assets?action=registerUpload"
                register_payload = {
                    "registerUploadRequest": {
                        "recipes": ["urn:li:digitalmediaRecipe:feedshare-image"],
                        "owner": self.author_urn,
                        "serviceRelationships": [
                            {
                                "relationshipType": "OWNER",
                                "identifier": "urn:li:userGeneratedContent"
                            }
                        ]
                    }
                }
                
                reg_resp = requests.post(register_url, headers=headers, json=register_payload)
                if reg_resp.status_code != 200:
                     return {"error": "LINKEDIN_REGISTER_ERROR", "message": reg_resp.json()}
                
                reg_data = reg_resp.json()
                upload_url = reg_data['value']['uploadMechanism']['com.linkedin.digitalmedia.uploading.MediaUploadHttpRequest']['uploadUrl']
                asset_urn = reg_data['value']['asset']

                # 1.2 Download Image
                img_resp = requests.get(media_url)
                if img_resp.status_code != 200:
                    return {"error": "IMAGE_DOWNLOAD_ERROR", "message": "Could not download image from OpenAI URL"}
                
                # 1.3 Upload Image Binary
                # LinkedIn requires no Authorization header for the upload PUT
                upload_headers = {"Content-Type": "application/octet-stream"}
                up_resp = requests.put(upload_url, headers=upload_headers, data=img_resp.content)
                
                if up_resp.status_code not in [200, 201]:
                    return {"error": "LINKEDIN_UPLOAD_ERROR", "message": "Failed to upload image binary to LinkedIn"}

            # Step 2: Create UGC Post
            post_url = "https://api.linkedin.com/v2/ugcPosts"
            
            share_content = {
                "shareCommentary": {
                    "text": text
                },
                "shareMediaCategory": "NONE"
            }

            if asset_urn:
                share_content["shareMediaCategory"] = "IMAGE"
                share_content["media"] = [
                    {
                        "status": "READY",
                        "description": {"text": "Generated by AI"},
                        "media": asset_urn,
                        "title": {"text": "AI Content"}
                    }
                ]

            post_payload = {
                "author": self.author_urn,
                "lifecycleState": "PUBLISHED",
                "specificContent": {
                    "com.linkedin.ugc.ShareContent": share_content
                },
                "visibility": {
                    "com.linkedin.ugc.MemberNetworkVisibility": "PUBLIC"
                }
            }

            post_resp = requests.post(post_url, headers=headers, json=post_payload)
            
            if post_resp.status_code in [200, 201]:
                return {"success": True, "id": post_resp.json().get("id")}
            else:
                return {"error": "LINKEDIN_POST_ERROR", "message": post_resp.json()}

        except Exception as e:
            return {"error": "EXCEPTION", "message": str(e)}
